# Generated by Django 4.2.4 on 2023-11-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_enrollment_membershipplan_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='timeStamp',
            new_name='joiningDate',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='timeStamp',
            new_name='joiningDate',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
