# Generated by Django 4.2.4 on 2023-11-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_rename_timestamp_enrollment_joiningdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='Gender',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
