# Generated by Django 4.2.4 on 2023-11-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_enrollment_gender_alter_trainer_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('addedtime', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
