# Generated by Django 4.2.4 on 2023-11-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_gallery_alter_enrollment_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_date', models.DateTimeField(auto_now_add=True)),
                ('login_time', models.CharField(max_length=100)),
                ('logout_time', models.CharField(max_length=100)),
                ('workout', models.CharField(choices=[('biceps', 'Biceps'), ('core', 'Core'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('chest', 'Chest')], max_length=10)),
                ('trainedBy', models.CharField(max_length=100)),
            ],
        ),
    ]
