# Generated by Django 4.2.4 on 2023-11-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='phonenumber',
            field=models.CharField(default=7428621255, max_length=15),
            preserve_default=False,
        ),
    ]
